export const data = [
  {
    id: 1,
    name: "Prenses Model Gelinlik",
    price: 12500,
    description: "Şık ve zarif prenses model gelinlik.",
    imageUrl: "https://example.com/dress1.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 12,
    category: "Prenses",
  },
  {
    id: 2,
    name: "Balık Kesim Gelinlik",
    price: 14000,
    description: "Modern ve vücuda oturan balık kesim.",
    imageUrl: "https://example.com/dress2.jpg",
    sizeOptions: ["34", "36", "38"],
    colorOptions: ["Beyaz", "Fildişi"],
    stock: 8,
    category: "Balık Kesim",
  },
  {
    id: 3,
    name: "A Kesim Gelinlik",
    price: 11000,
    description: "Klasik ve rahat A kesim gelinlik.",
    imageUrl: "https://example.com/dress3.jpg",
    sizeOptions: ["38", "40", "42", "44"],
    colorOptions: ["Beyaz", "Pembe"],
    stock: 15,
    category: "A Kesim",
  },
  {
    id: 4,
    name: "Vintage Gelinlik",
    price: 15500,
    description: "Nostaljik bir tarz sunan vintage gelinlik.",
    imageUrl: "https://example.com/dress4.jpg",
    sizeOptions: ["36", "38", "40"],
    colorOptions: ["Fildişi", "Krem"],
    stock: 10,
    category: "Vintage",
  },
  {
    id: 5,
    name: "Dantel İşlemeli Gelinlik",
    price: 16500,
    description: "Detaylı dantel işlemelerle dikkat çeken gelinlik.",
    imageUrl: "https://example.com/dress5.jpg",
    sizeOptions: ["34", "36", "38", "40"],
    colorOptions: ["Beyaz"],
    stock: 9,
    category: "Dantel",
  },
  {
    id: 6,
    name: "Bohem Tarz Gelinlik",
    price: 12000,
    description: "Rahat ve doğal bohem tarz gelinlik.",
    imageUrl: "https://example.com/dress6.jpg",
    sizeOptions: ["38", "40", "42"],
    colorOptions: ["Krem", "Beyaz"],
    stock: 14,
    category: "Bohem",
  },
  {
    id: 7,
    name: "Sade Gelinlik",
    price: 9500,
    description: "Minimal tasarımı sevenler için sade model.",
    imageUrl: "https://example.com/dress7.jpg",
    sizeOptions: ["36", "38", "40"],
    colorOptions: ["Beyaz", "Fildişi"],
    stock: 18,
    category: "Sade",
  },
  {
    id: 8,
    name: "Kabarık Gelinlik",
    price: 18000,
    description: "Etkileyici kabarık tasarımıyla dikkat çeker.",
    imageUrl: "https://example.com/dress8.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 7,
    category: "Kabarık",
  },
  {
    id: 9,
    name: "Taş İşlemeli Gelinlik",
    price: 20000,
    description: "Göz alıcı taş işlemeleriyle öne çıkar.",
    imageUrl: "https://example.com/dress9.jpg",
    sizeOptions: ["36", "38", "40"],
    colorOptions: ["Beyaz", "Gümüş"],
    stock: 5,
    category: "Taş İşlemeli",
  },
  {
    id: 10,
    name: "Uzun Kollu Gelinlik",
    price: 13000,
    description: "Soğuk havalar için uzun kollu şık tasarım.",
    imageUrl: "https://example.com/dress10.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 10,
    category: "Uzun Kollu",
  },
];
