const productData = [
  {
    id: 1,
    name: "Prenses Model Gelinlik",
    price: 12500,
    description: "Şık ve zarif prenses model gelinlik.",
    imageUrl: "https://i.pinimg.com/736x/91/cf/2d/91cf2d1bdcda74ebae65914acdda841f.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 12,
    category: "Prenses",
  },
  {
    id: 11,
    name: "Prenses Model Gelinlik",
    price: 12500,
    description: "Şık ve zarif prenses model gelinlik.",
    imageUrl: "https://aysirashop.com/Content/Uploads/Products/1628/1792/m_028_9285_1708.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 12,
    category: "Prenses",
  },
  {
    id: 2,
    name: "Balık Kesim Gelinlik",
    price: 10000,
    description: "Modern ve vücuda oturan balık kesim.",
    imageUrl: "https://i.dugun.com/articles/body/original_balik-gelinlik.jpg.jpg",
    sizeOptions: ["34", "36", "38"],
    colorOptions: ["Beyaz", "Fildişi"],
    stock: 8,
    category: "Balık Kesim",
  },
  {
    id: 12,
    name: "Vintage Gelinlik",
    price: 10000,
    description: "Modern ve vücuda oturan balık kesim.",
    imageUrl: "https://aysirashop.com/Content/Uploads/Products/1873/2062/m_078_8227_2702.jpg",
    sizeOptions: ["34", "36", "38"],
    colorOptions: ["Beyaz", "Fildişi"],
    stock: 8,
    category: "Vintage",
  },
  {
    id: 3,
    name: "A Kesim Gelinlik",
    price: 11000,
    description: "Klasik ve rahat A kesim gelinlik.",
    imageUrl: "https://ideacdn.net/idea/jn/11/myassets/products/167/dali-005-0171.jpg?revision=1723099675",
    sizeOptions: ["38", "40", "42", "44"],
    colorOptions: ["Beyaz", "Pembe"],
    stock: 15,
    category: "A Kesim",
  },
  {
    id: 4,
    name: "Vintage Gelinlik",
    price: 15500,
    description: "Nostaljik bir tarz sunan vintage gelinlik.",
    imageUrl: "https://newinstyle.com.tr/images/makaleler/Yitmacli-A-Kesim-Gelinlik-resim-9-resim-16.jpg",
    sizeOptions: ["36", "38", "40"],
    colorOptions: ["Fildişi", "Krem"],
    stock: 10,
    category: "Vintage",
  },
  {
    id: 5,
    name: "Dantel İşlemeli Gelinlik",
    price: 16500,
    description: "Detaylı dantel işlemelerle dikkat çeken gelinlik.",
    imageUrl: "https://ideacdn.net/idea/jn/11/myassets/products/658/violetta-on.jpg?revision=1723893862",
    sizeOptions: ["34", "36", "38", "40"],
    colorOptions: ["Beyaz"],
    stock: 9,
    category: "Dantel",
  },
  {
    id: 6,
    name: "Bohem Tarz Gelinlik",
    price: 12000,
    description: "Rahat ve doğal bohem tarz gelinlik.",
    imageUrl: "https://www.narinmoda.com/Panel/dashboard/Uploads/Product/Detail/Gallery/Helen_ve_Bohem_Gelinlik_Model_1251_1_.jpg",
    sizeOptions: ["38", "40", "42"],
    colorOptions: ["Krem", "Beyaz"],
    stock: 14,
    category: "Bohem",
  },
  {
    id: 7,
    name: "Sade Gelinlik",
    price: 9500,
    description: "Minimal tasarımı sevenler için sade model.",
    imageUrl: "https://cdn-europe.dugunbuketi.com/media/7888/conversions/sade-gelinlik-modelleri-5-md.jpg",
    sizeOptions: ["36", "38", "40"],
    colorOptions: ["Beyaz", "Fildişi"],
    stock: 18,
    category: "Sade",
  },
  {
    id: 8,
    name: "Kabarık Gelinlik",
    price: 18000,
    description: "Etkileyici kabarık tasarımıyla dikkat çeker.",
    imageUrl: "https://www.yesimgelinlik.com/wp-content/uploads/2022/08/kol-tas-islemeli-derin-v-yaka-prenses-gelinlik-5335544248.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 7,
    category: "Kabarık",
  },
  {
    id: 9,
    name: "Taş İşlemeli Gelinlik",
    price: 20000,
    description: "Göz alıcı taş işlemeleriyle öne çıkar.",
    imageUrl: "https://i0.wp.com/www.gelinlik.co/wp-content/uploads/2019/04/Bijoux-Ta%C5%9F-%C4%B0%C5%9Flemeli-Gelinlik-Modeli.jpg?fit=800%2C1200&ssl=1",
    sizeOptions: ["36", "38", "40"],
    colorOptions: ["Beyaz", "Gümüş"],
    stock: 5,
    category: "Taş İşlemeli",
  },
  {
    id: 10,
    name: "Uzun Kollu Gelinlik",
    price: 13000,
    description: "Soğuk havalar için uzun kollu şık tasarım.",
    imageUrl: "https://www.abiyefon.com/images/default/image/24330/121647910_0.jpg",
    sizeOptions: ["36", "38", "40", "42"],
    colorOptions: ["Beyaz", "Krem"],
    stock: 10,
    category: "Uzun Kollu",
  },
];

export default productData;
